import {
  BuildingsBold,
  EyeBold,
  EyeClosedBold,
  ForbiddenCircleBold,
  GraphNewUpBold,
  LetterBold,
  LockKeyholeMinimalisticBold,
  MagnifierBold,
  MapBold,
  MapPointBold,
  NotebookBold,
  Pen2Bold,
  PhoneCallingBold,
  ShieldUserBold,
  StarBold,
  UserBlockRoundedBold,
  UserCheckRoundedBold,
  UserCrossRoundedBold,
  UserHandUpLineDuotone,
  UserRoundedBold,
  UsersGroupRoundedBold,
  WalletBold,
  StarsBoldDuotone,
} from '@solar-icons/angular'
import { provideSolarIcons } from '@solar-icons/angular'

export const appIconsConfig = [
  provideSolarIcons({
    BuildingsBold,
    StarsBoldDuotone,
    EyeBold,
    EyeClosedBold,
    ForbiddenCircleBold,
    GraphNewUpBold,
    LetterBold,
    LockKeyholeMinimalisticBold,
    MagnifierBold,
    MapBold,
    MapPointBold,
    NotebookBold,
    Pen2Bold,
    PhoneCallingBold,
    ShieldUserBold,
    StarBold,
    UserBlockRoundedBold,
    UserCheckRoundedBold,
    UserCrossRoundedBold,
    UserHandUpLineDuotone,
    UserRoundedBold,
    UsersGroupRoundedBold,
    WalletBold,
  }),
]
